paths:
  base_dir: "/home/liangqing/AcademicAgent-Suite"
  raw_storage: "/home/liangqing/AcademicAgent-Suite/storage/raw"
  processed_storage: "/home/liangqing/AcademicAgent-Suite/storage/processed"

environments:
  doc_recognize: "/home/liangqing/AcademicAgent-Suite/envs/DocRecognize/bin/python"
  video_recognize: "/home/liangqing/miniconda3/envs/VideoRecognize/bin/python"
  visual_inference: "/home/liangqing/AcademicAgent-Suite/envs/VisualInference/bin/python"
  sandbox_inference: "/home/liangqing/AcademicAgent-Suite/envs/SandboxInference/bin/python"
  data_stream: "/home/liangqing/AcademicAgent-Suite/envs/DataStream/bin/python"
  agent_logic: "/home/liangqing/AcademicAgent-Suite/envs/AgentLogic/bin/python"
  
model_paths:
  whisper: "/home/liangqing/AcademicAgent-Suite/models/whisper_v3"
  qwen2_vl: "/home/liangqing/AcademicAgent-Suite/models/qwen2_vl"
  miner_u: "/home/liangqing/AcademicAgent-Suite/models/miner_u"
  clip: "/home/liangqing/AcademicAgent-Suite/models/clip"
  dinov2: "/home/liangqing/AcademicAgent-Suite/models/dinov2/"
  
database:
  milvus_host: "localhost"
  milvus_port: "19530"
  redis_host: "localhost"
  redis_port: "6379"